sudo: false
language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.3
before_install: gem install bundler -v 1.15.0
script: 'bundle exec rake'

services:
  - redis-server

notifications:
  email:
    recipients:
      - pamit.edu@gmail.com
    on_failure: change
    on_success: never
